apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: react-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata: 
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
          - name: {{ .Values.appName }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            ports:
            - containerPort: {{ .Values.service.port }}