# Default values for react.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: amirad1/react
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "10"

appName: "react-app"

service:
  type: NodePort
  port: 80
  nodePort: 30750
